name: swalayam_ku
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  module_auth:
    path: package/module_auth
  module_core:
    path: package/module_core
  module_user:
    path: package/module_user
  module_admin:
    path: package/module_admin
  riverpod: ^3.1.0
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1
  json_annotation: ^4.9.0
  lottie: ^3.3.2
  meta: ^1.17.0
  go_router: ^17.0.1
  flutter_svg: ^2.2.3
  flutter_secure_storage: ^10.0.0
  google_fonts: ^7.0.0
  get_it: ^9.2.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_functions: ^6.0.5
  logger: ^2.6.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/logo/
